# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主界面.ui',
# licensing of '主界面.ui' applies.
#
# Created: Mon Jun 15 21:27:49 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1175, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/主题.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 505))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ZhuCaiDan = QtWidgets.QTabWidget(self.centralwidget)
        self.ZhuCaiDan.setEnabled(True)
        self.ZhuCaiDan.setMouseTracking(True)
        self.ZhuCaiDan.setTabletTracking(True)
        self.ZhuCaiDan.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ZhuCaiDan.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ZhuCaiDan.setAcceptDrops(True)
        self.ZhuCaiDan.setToolTipDuration(-1)
        self.ZhuCaiDan.setStatusTip("")
        self.ZhuCaiDan.setAutoFillBackground(False)
        self.ZhuCaiDan.setStyleSheet("")
        self.ZhuCaiDan.setDocumentMode(False)
        self.ZhuCaiDan.setTabsClosable(True)
        self.ZhuCaiDan.setMovable(False)
        self.ZhuCaiDan.setTabBarAutoHide(False)
        self.ZhuCaiDan.setObjectName("ZhuCaiDan")
        self.ranwu = QtWidgets.QWidget()
        self.ranwu.setObjectName("ranwu")
        self.ZhuCaiDan.addTab(self.ranwu, "")
        self.zhicaidan = QtWidgets.QWidget()
        self.zhicaidan.setObjectName("zhicaidan")
        self.ZhuCaiDan.addTab(self.zhicaidan, "")
        self.renyuanxinxi = QtWidgets.QWidget()
        self.renyuanxinxi.setObjectName("renyuanxinxi")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.renyuanxinxi)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.renyuanxinxi)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 62))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 439, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 8, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 6, 1, 1)
        self.ryxx_tuichu = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/png/1110305.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_tuichu.setIcon(icon1)
        self.ryxx_tuichu.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_tuichu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_tuichu.setAutoRaise(True)
        self.ryxx_tuichu.setObjectName("ryxx_tuichu")
        self.gridLayout.addWidget(self.ryxx_tuichu, 0, 10, 1, 1)
        self.ryxx_chakan = QtWidgets.QToolButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ICO/png/1081662.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_chakan.setIcon(icon2)
        self.ryxx_chakan.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_chakan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_chakan.setAutoRaise(True)
        self.ryxx_chakan.setObjectName("ryxx_chakan")
        self.gridLayout.addWidget(self.ryxx_chakan, 0, 4, 1, 1)
        self.ryxx_xinzeng = QtWidgets.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/png/1081676.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_xinzeng.setIcon(icon3)
        self.ryxx_xinzeng.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_xinzeng.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_xinzeng.setAutoRaise(True)
        self.ryxx_xinzeng.setObjectName("ryxx_xinzeng")
        self.gridLayout.addWidget(self.ryxx_xinzeng, 0, 0, 1, 1)
        self.ryxx_xiugai = QtWidgets.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/png/1073170.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_xiugai.setIcon(icon4)
        self.ryxx_xiugai.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_xiugai.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_xiugai.setAutoRaise(True)
        self.ryxx_xiugai.setObjectName("ryxx_xiugai")
        self.gridLayout.addWidget(self.ryxx_xiugai, 0, 2, 1, 1)
        self.ryxx_liuchengtiaozhuan = QtWidgets.QToolButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/png/1081628.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_liuchengtiaozhuan.setIcon(icon5)
        self.ryxx_liuchengtiaozhuan.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_liuchengtiaozhuan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_liuchengtiaozhuan.setAutoRaise(True)
        self.ryxx_liuchengtiaozhuan.setObjectName("ryxx_liuchengtiaozhuan")
        self.gridLayout.addWidget(self.ryxx_liuchengtiaozhuan, 0, 7, 1, 1)
        self.ryxx_shanchu = QtWidgets.QToolButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/png/1081640.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_shanchu.setIcon(icon6)
        self.ryxx_shanchu.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_shanchu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_shanchu.setAutoRaise(True)
        self.ryxx_shanchu.setObjectName("ryxx_shanchu")
        self.gridLayout.addWidget(self.ryxx_shanchu, 0, 1, 1, 1)
        self.ryxx_daochu = QtWidgets.QToolButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/png/1081656.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_daochu.setIcon(icon7)
        self.ryxx_daochu.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_daochu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_daochu.setAutoRaise(True)
        self.ryxx_daochu.setObjectName("ryxx_daochu")
        self.gridLayout.addWidget(self.ryxx_daochu, 0, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.ryxx_chaxun = QtWidgets.QToolButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ICO/png/1168148.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ryxx_chaxun.setIcon(icon8)
        self.ryxx_chaxun.setIconSize(QtCore.QSize(36, 36))
        self.ryxx_chaxun.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ryxx_chaxun.setAutoRaise(True)
        self.ryxx_chaxun.setObjectName("ryxx_chaxun")
        self.gridLayout.addWidget(self.ryxx_chaxun, 0, 9, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.groupBox = QtWidgets.QGroupBox(self.renyuanxinxi)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.ryxx_gonghao__text = QtWidgets.QLineEdit(self.groupBox)
        self.ryxx_gonghao__text.setGeometry(QtCore.QRect(190, 10, 81, 20))
        self.ryxx_gonghao__text.setMinimumSize(QtCore.QSize(81, 20))
        self.ryxx_gonghao__text.setMaximumSize(QtCore.QSize(81, 20))
        self.ryxx_gonghao__text.setObjectName("ryxx_gonghao__text")
        self.ryxx_xingming = QtWidgets.QLineEdit(self.groupBox)
        self.ryxx_xingming.setGeometry(QtCore.QRect(320, 10, 81, 20))
        self.ryxx_xingming.setMinimumSize(QtCore.QSize(81, 20))
        self.ryxx_xingming.setMaximumSize(QtCore.QSize(81, 20))
        self.ryxx_xingming.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ryxx_xingming.setObjectName("ryxx_xingming")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(555, 11, 31, 16))
        self.label_5.setMaximumSize(QtCore.QSize(36, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_2.setMaximumSize(QtCore.QSize(36, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 11, 31, 16))
        self.label_3.setMaximumSize(QtCore.QSize(36, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(290, 11, 31, 16))
        self.label_4.setMaximumSize(QtCore.QSize(36, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(680, 10, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        self.label_13.setObjectName("label_13")
        self.ryxx_shaixuan = QtWidgets.QComboBox(self.groupBox)
        self.ryxx_shaixuan.setGeometry(QtCore.QRect(470, 10, 81, 22))
        self.ryxx_shaixuan.setObjectName("ryxx_shaixuan")
        self.ryxx_shaixuan.addItem("")
        self.ryxx_shaixuan.addItem("")
        self.ryxx_shaixuan.addItem("")
        self.ryxx_shaixuan.addItem("")
        self.ryxx_bumen_text = QtWidgets.QComboBox(self.groupBox)
        self.ryxx_bumen_text.setGeometry(QtCore.QRect(40, 10, 111, 20))
        self.ryxx_bumen_text.setMaximumSize(QtCore.QSize(800, 20))
        self.ryxx_bumen_text.setEditable(True)
        self.ryxx_bumen_text.setObjectName("ryxx_bumen_text")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(790, 5, 291, 31))
        self.textEdit.setObjectName("textEdit")
        self.ryxx_Q_riqi = QtWidgets.QLineEdit(self.groupBox)
        self.ryxx_Q_riqi.setGeometry(QtCore.QRect(590, 10, 91, 21))
        self.ryxx_Q_riqi.setObjectName("ryxx_Q_riqi")
        self.ryxx_J_riqi = QtWidgets.QLineEdit(self.groupBox)
        self.ryxx_J_riqi.setGeometry(QtCore.QRect(690, 10, 91, 21))
        self.ryxx_J_riqi.setObjectName("ryxx_J_riqi")
        self.verticalLayout.addWidget(self.groupBox)
        self.ryxx_tableWidget = QtWidgets.QTableWidget(self.renyuanxinxi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ryxx_tableWidget.sizePolicy().hasHeightForWidth())
        self.ryxx_tableWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ryxx_tableWidget.setPalette(palette)
        self.ryxx_tableWidget.setAutoScroll(True)
        self.ryxx_tableWidget.setObjectName("ryxx_tableWidget")
        self.ryxx_tableWidget.setColumnCount(0)
        self.ryxx_tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.ryxx_tableWidget)
        self.ZhuCaiDan.addTab(self.renyuanxinxi, "")
        self.xiangmuxinxi = QtWidgets.QWidget()
        self.xiangmuxinxi.setObjectName("xiangmuxinxi")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.xiangmuxinxi)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.xiangmuxinxi)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 62))
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget_5 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1, 1, 439, 60))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.xmxx_tuichu = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_tuichu.setIcon(icon1)
        self.xmxx_tuichu.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_tuichu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_tuichu.setAutoRaise(True)
        self.xmxx_tuichu.setObjectName("xmxx_tuichu")
        self.gridLayout_6.addWidget(self.xmxx_tuichu, 0, 10, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 0, 3, 1, 1)
        self.xmxx_liuchengtiaozhuan = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_liuchengtiaozhuan.setIcon(icon5)
        self.xmxx_liuchengtiaozhuan.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_liuchengtiaozhuan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_liuchengtiaozhuan.setAutoRaise(True)
        self.xmxx_liuchengtiaozhuan.setObjectName("xmxx_liuchengtiaozhuan")
        self.gridLayout_6.addWidget(self.xmxx_liuchengtiaozhuan, 0, 7, 1, 1)
        self.xmxx_daochu = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_daochu.setIcon(icon7)
        self.xmxx_daochu.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_daochu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_daochu.setAutoRaise(True)
        self.xmxx_daochu.setObjectName("xmxx_daochu")
        self.gridLayout_6.addWidget(self.xmxx_daochu, 0, 5, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 0, 8, 1, 1)
        self.xmxx_xiugai = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_xiugai.setIcon(icon4)
        self.xmxx_xiugai.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_xiugai.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_xiugai.setAutoRaise(True)
        self.xmxx_xiugai.setObjectName("xmxx_xiugai")
        self.gridLayout_6.addWidget(self.xmxx_xiugai, 0, 2, 1, 1)
        self.xmxx_xinzeng = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_xinzeng.setIcon(icon3)
        self.xmxx_xinzeng.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_xinzeng.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_xinzeng.setAutoRaise(True)
        self.xmxx_xinzeng.setObjectName("xmxx_xinzeng")
        self.gridLayout_6.addWidget(self.xmxx_xinzeng, 0, 0, 1, 1)
        self.xmxx_chakan = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_chakan.setIcon(icon2)
        self.xmxx_chakan.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_chakan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_chakan.setAutoRaise(True)
        self.xmxx_chakan.setObjectName("xmxx_chakan")
        self.gridLayout_6.addWidget(self.xmxx_chakan, 0, 4, 1, 1)
        self.xmxx_shanchu = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_shanchu.setIcon(icon6)
        self.xmxx_shanchu.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_shanchu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_shanchu.setAutoRaise(True)
        self.xmxx_shanchu.setObjectName("xmxx_shanchu")
        self.gridLayout_6.addWidget(self.xmxx_shanchu, 0, 1, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget_5)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_6.addWidget(self.line_13, 0, 6, 1, 1)
        self.xmxx_chaxun = QtWidgets.QToolButton(self.layoutWidget_5)
        self.xmxx_chaxun.setIcon(icon8)
        self.xmxx_chaxun.setIconSize(QtCore.QSize(36, 36))
        self.xmxx_chaxun.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.xmxx_chaxun.setAutoRaise(True)
        self.xmxx_chaxun.setObjectName("xmxx_chaxun")
        self.gridLayout_6.addWidget(self.xmxx_chaxun, 0, 9, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.xiangmuxinxi)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(755, 12, 31, 16))
        self.label_12.setMaximumSize(QtCore.QSize(36, 16))
        self.label_12.setObjectName("label_12")
        self.xmxx_J_riqi = QtWidgets.QDateEdit(self.groupBox_3)
        self.xmxx_J_riqi.setGeometry(QtCore.QRect(897, 11, 88, 20))
        self.xmxx_J_riqi.setMinimumSize(QtCore.QSize(88, 20))
        self.xmxx_J_riqi.setMaximumSize(QtCore.QSize(88, 20))
        self.xmxx_J_riqi.setCalendarPopup(True)
        self.xmxx_J_riqi.setObjectName("xmxx_J_riqi")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_14.setMaximumSize(QtCore.QSize(36, 16))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(120, 10, 31, 16))
        self.label_15.setMaximumSize(QtCore.QSize(36, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(880, 11, 16, 16))
        self.label_17.setObjectName("label_17")
        self.xmxx_Q_riqi = QtWidgets.QDateEdit(self.groupBox_3)
        self.xmxx_Q_riqi.setGeometry(QtCore.QRect(787, 11, 88, 20))
        self.xmxx_Q_riqi.setMinimumSize(QtCore.QSize(88, 20))
        self.xmxx_Q_riqi.setMaximumSize(QtCore.QSize(88, 20))
        self.xmxx_Q_riqi.setCalendarPopup(True)
        self.xmxx_Q_riqi.setObjectName("xmxx_Q_riqi")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(610, 10, 60, 20))
        self.label_18.setMaximumSize(QtCore.QSize(60, 20))
        self.label_18.setObjectName("label_18")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 9, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.xmxx_kehu = QtWidgets.QComboBox(self.groupBox_3)
        self.xmxx_kehu.setGeometry(QtCore.QRect(40, 9, 69, 22))
        self.xmxx_kehu.setEditable(True)
        self.xmxx_kehu.setObjectName("xmxx_kehu")
        self.xmxx_neibubianhao = QtWidgets.QComboBox(self.groupBox_3)
        self.xmxx_neibubianhao.setGeometry(QtCore.QRect(150, 9, 69, 22))
        self.xmxx_neibubianhao.setEditable(True)
        self.xmxx_neibubianhao.setObjectName("xmxx_neibubianhao")
        self.xmxx_kehubianhao = QtWidgets.QComboBox(self.groupBox_3)
        self.xmxx_kehubianhao.setGeometry(QtCore.QRect(290, 9, 111, 22))
        self.xmxx_kehubianhao.setEditable(True)
        self.xmxx_kehubianhao.setObjectName("xmxx_kehubianhao")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(230, 10, 61, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(420, 10, 51, 20))
        self.label_20.setMaximumSize(QtCore.QSize(60, 20))
        self.label_20.setObjectName("label_20")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(510, 9, 81, 22))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.xmxx_shaixuan = QtWidgets.QComboBox(self.groupBox_3)
        self.xmxx_shaixuan.setGeometry(QtCore.QRect(670, 10, 51, 22))
        self.xmxx_shaixuan.setObjectName("xmxx_shaixuan")
        self.xmxx_shaixuan.addItem("")
        self.xmxx_shaixuan.addItem("")
        self.xmxx_shaixuan.addItem("")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(990, 2, 89, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(990, 20, 89, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.xmxx_tableWidget = QtWidgets.QTableWidget(self.xiangmuxinxi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmxx_tableWidget.sizePolicy().hasHeightForWidth())
        self.xmxx_tableWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.xmxx_tableWidget.setPalette(palette)
        self.xmxx_tableWidget.setAutoScroll(True)
        self.xmxx_tableWidget.setObjectName("xmxx_tableWidget")
        self.xmxx_tableWidget.setColumnCount(15)
        self.xmxx_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.xmxx_tableWidget.setHorizontalHeaderItem(14, item)
        self.verticalLayout_2.addWidget(self.xmxx_tableWidget)
        self.ZhuCaiDan.addTab(self.xiangmuxinxi, "")
        self.jiancebaogao = QtWidgets.QWidget()
        self.jiancebaogao.setObjectName("jiancebaogao")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.jiancebaogao)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.jiancebaogao)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 62))
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(1, 1, 390, 60))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.toolButton_15 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_15.setIcon(icon1)
        self.toolButton_15.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_15.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_15.setAutoRaise(True)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout_4.addWidget(self.toolButton_15, 0, 9, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_16.setIcon(icon2)
        self.toolButton_16.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_16.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_16.setAutoRaise(True)
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout_4.addWidget(self.toolButton_16, 0, 4, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_17.setIcon(icon4)
        self.toolButton_17.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_17.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_17.setAutoRaise(True)
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout_4.addWidget(self.toolButton_17, 0, 2, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_18.setIcon(icon5)
        self.toolButton_18.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_18.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_18.setAutoRaise(True)
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout_4.addWidget(self.toolButton_18, 0, 7, 1, 1)
        self.toolButton_19 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_19.setIcon(icon6)
        self.toolButton_19.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_19.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_19.setAutoRaise(True)
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout_4.addWidget(self.toolButton_19, 0, 1, 1, 1)
        self.toolButton_20 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_20.setIcon(icon7)
        self.toolButton_20.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_20.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_20.setAutoRaise(True)
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout_4.addWidget(self.toolButton_20, 0, 5, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 0, 6, 1, 1)
        self.toolButton_21 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_21.setIcon(icon3)
        self.toolButton_21.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_21.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_21.setAutoRaise(True)
        self.toolButton_21.setObjectName("toolButton_21")
        self.gridLayout_4.addWidget(self.toolButton_21, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_4.addWidget(self.line_8, 0, 8, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_4.addWidget(self.line_9, 0, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.jiancebaogao)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.chaxun_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.chaxun_3.setEnabled(True)
        self.chaxun_3.setGeometry(QtCore.QRect(1020, 10, 75, 23))
        self.chaxun_3.setObjectName("chaxun_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(685, 12, 31, 16))
        self.label_16.setMaximumSize(QtCore.QSize(36, 16))
        self.label_16.setObjectName("label_16")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit_5.setGeometry(QtCore.QRect(827, 11, 88, 20))
        self.dateEdit_5.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_5.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_5.setCalendarPopup(True)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_21.setMaximumSize(QtCore.QSize(36, 16))
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(120, 10, 31, 16))
        self.label_22.setMaximumSize(QtCore.QSize(36, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(810, 11, 16, 16))
        self.label_23.setObjectName("label_23")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit_6.setGeometry(QtCore.QRect(717, 11, 88, 20))
        self.dateEdit_6.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_6.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_6.setCalendarPopup(True)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_10.setGeometry(QtCore.QRect(40, 9, 69, 22))
        self.comboBox_10.setEditable(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_11.setGeometry(QtCore.QRect(150, 9, 69, 22))
        self.comboBox_11.setEditable(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_12.setGeometry(QtCore.QRect(290, 9, 111, 22))
        self.comboBox_12.setEditable(True)
        self.comboBox_12.setObjectName("comboBox_12")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(230, 10, 61, 20))
        self.label_25.setObjectName("label_25")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(920, 2, 89, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(920, 20, 89, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_18.setGeometry(QtCore.QRect(450, 10, 51, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(420, 10, 31, 20))
        self.label_33.setMaximumSize(QtCore.QSize(60, 20))
        self.label_33.setObjectName("label_33")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(520, 10, 60, 20))
        self.label_31.setMaximumSize(QtCore.QSize(60, 20))
        self.label_31.setObjectName("label_31")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(580, 10, 81, 20))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(81, 20))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(81, 20))
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setClearButtonEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.tableWidget_jc = QtWidgets.QTableWidget(self.jiancebaogao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_jc.sizePolicy().hasHeightForWidth())
        self.tableWidget_jc.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget_jc.setPalette(palette)
        self.tableWidget_jc.setAutoScroll(True)
        self.tableWidget_jc.setObjectName("tableWidget_jc")
        self.tableWidget_jc.setColumnCount(0)
        self.tableWidget_jc.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_jc)
        self.ZhuCaiDan.addTab(self.jiancebaogao, "")
        self.yanmoxingxi = QtWidgets.QWidget()
        self.yanmoxingxi.setObjectName("yanmoxingxi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.yanmoxingxi)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.yanmoxingxi)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 62))
        self.widget_4.setObjectName("widget_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(1, 1, 390, 60))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolButton_22 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_22.setIcon(icon1)
        self.toolButton_22.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_22.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_22.setAutoRaise(True)
        self.toolButton_22.setObjectName("toolButton_22")
        self.gridLayout_5.addWidget(self.toolButton_22, 0, 9, 1, 1)
        self.toolButton_23 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_23.setIcon(icon2)
        self.toolButton_23.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_23.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_23.setAutoRaise(True)
        self.toolButton_23.setObjectName("toolButton_23")
        self.gridLayout_5.addWidget(self.toolButton_23, 0, 4, 1, 1)
        self.toolButton_24 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_24.setIcon(icon4)
        self.toolButton_24.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_24.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_24.setAutoRaise(True)
        self.toolButton_24.setObjectName("toolButton_24")
        self.gridLayout_5.addWidget(self.toolButton_24, 0, 2, 1, 1)
        self.toolButton_25 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_25.setIcon(icon5)
        self.toolButton_25.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_25.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_25.setAutoRaise(True)
        self.toolButton_25.setObjectName("toolButton_25")
        self.gridLayout_5.addWidget(self.toolButton_25, 0, 7, 1, 1)
        self.toolButton_26 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_26.setIcon(icon6)
        self.toolButton_26.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_26.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_26.setAutoRaise(True)
        self.toolButton_26.setObjectName("toolButton_26")
        self.gridLayout_5.addWidget(self.toolButton_26, 0, 1, 1, 1)
        self.toolButton_27 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_27.setIcon(icon7)
        self.toolButton_27.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_27.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_27.setAutoRaise(True)
        self.toolButton_27.setObjectName("toolButton_27")
        self.gridLayout_5.addWidget(self.toolButton_27, 0, 5, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_5.addWidget(self.line_10, 0, 6, 1, 1)
        self.toolButton_28 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_28.setIcon(icon3)
        self.toolButton_28.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_28.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_28.setAutoRaise(True)
        self.toolButton_28.setObjectName("toolButton_28")
        self.gridLayout_5.addWidget(self.toolButton_28, 0, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_5.addWidget(self.line_11, 0, 8, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_5.addWidget(self.line_12, 0, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.yanmoxingxi)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.chaxun_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.chaxun_4.setEnabled(True)
        self.chaxun_4.setGeometry(QtCore.QRect(920, 10, 75, 23))
        self.chaxun_4.setObjectName("chaxun_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(585, 12, 31, 16))
        self.label_24.setMaximumSize(QtCore.QSize(36, 16))
        self.label_24.setObjectName("label_24")
        self.dateEdit_7 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_7.setGeometry(QtCore.QRect(727, 11, 88, 20))
        self.dateEdit_7.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_7.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_7.setCalendarPopup(True)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_26.setMaximumSize(QtCore.QSize(36, 16))
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(120, 10, 31, 16))
        self.label_27.setMaximumSize(QtCore.QSize(36, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(710, 11, 16, 16))
        self.label_28.setObjectName("label_28")
        self.dateEdit_8 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_8.setGeometry(QtCore.QRect(617, 11, 88, 20))
        self.dateEdit_8.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_8.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_8.setCalendarPopup(True)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_13.setGeometry(QtCore.QRect(40, 9, 69, 22))
        self.comboBox_13.setEditable(True)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_14.setGeometry(QtCore.QRect(150, 9, 69, 22))
        self.comboBox_14.setEditable(True)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_15.setGeometry(QtCore.QRect(290, 9, 111, 22))
        self.comboBox_15.setEditable(True)
        self.comboBox_15.setObjectName("comboBox_15")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(230, 10, 61, 20))
        self.label_29.setObjectName("label_29")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_7.setGeometry(QtCore.QRect(820, 2, 89, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_8.setGeometry(QtCore.QRect(820, 20, 89, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(420, 10, 60, 20))
        self.label_38.setMaximumSize(QtCore.QSize(60, 20))
        self.label_38.setObjectName("label_38")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(480, 10, 81, 20))
        self.lineEdit_10.setMinimumSize(QtCore.QSize(81, 20))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(81, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.tableWidget_ym = QtWidgets.QTableWidget(self.yanmoxingxi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_ym.sizePolicy().hasHeightForWidth())
        self.tableWidget_ym.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget_ym.setPalette(palette)
        self.tableWidget_ym.setAutoScroll(True)
        self.tableWidget_ym.setObjectName("tableWidget_ym")
        self.tableWidget_ym.setColumnCount(0)
        self.tableWidget_ym.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_ym)
        self.ZhuCaiDan.addTab(self.yanmoxingxi, "")
        self.jishiben = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.jishiben.sizePolicy().hasHeightForWidth())
        self.jishiben.setSizePolicy(sizePolicy)
        self.jishiben.setAutoFillBackground(True)
        self.jishiben.setObjectName("jishiben")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.jishiben)
        self.calendarWidget.setGeometry(QtCore.QRect(1, 1, 248, 197))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.jishiben)
        self.label.setGeometry(QtCore.QRect(399, 1, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.jishiben)
        self.textBrowser.setGeometry(QtCore.QRect(399, 27, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.ZhuCaiDan.addTab(self.jishiben, "")
        self.gridLayout_3.addWidget(self.ZhuCaiDan, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.caidan = QtWidgets.QMenuBar(MainWindow)
        self.caidan.setGeometry(QtCore.QRect(0, 0, 1175, 23))
        self.caidan.setObjectName("caidan")
        self.ren_shi = QtWidgets.QMenu(self.caidan)
        self.ren_shi.setObjectName("ren_shi")
        self.xiang_mu = QtWidgets.QMenu(self.caidan)
        self.xiang_mu.setObjectName("xiang_mu")
        self.sheng_chan = QtWidgets.QMenu(self.caidan)
        self.sheng_chan.setObjectName("sheng_chan")
        self.pin_zhi = QtWidgets.QMenu(self.caidan)
        self.pin_zhi.setObjectName("pin_zhi")
        self.chang_ku = QtWidgets.QMenu(self.caidan)
        self.chang_ku.setObjectName("chang_ku")
        self.cai_wu = QtWidgets.QMenu(self.caidan)
        self.cai_wu.setObjectName("cai_wu")
        self.ti_xi = QtWidgets.QMenu(self.caidan)
        self.ti_xi.setTearOffEnabled(False)
        self.ti_xi.setObjectName("ti_xi")
        self.zong_he_fen_xi = QtWidgets.QMenu(self.caidan)
        self.zong_he_fen_xi.setObjectName("zong_he_fen_xi")
        self.chang_yong_ruan_jian = QtWidgets.QMenu(self.caidan)
        self.chang_yong_ruan_jian.setObjectName("chang_yong_ruan_jian")
        self.bang_zhu = QtWidgets.QMenu(self.caidan)
        self.bang_zhu.setObjectName("bang_zhu")
        MainWindow.setMenuBar(self.caidan)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actFont_ranyuanchaxun = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(267).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_ranyuanchaxun.setIcon(icon9)
        self.actFont_ranyuanchaxun.setObjectName("actFont_ranyuanchaxun")
        self.加班记录 = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ICO/png/1218679.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.加班记录.setIcon(icon10)
        self.加班记录.setObjectName("加班记录")
        self.请假记录 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ICO/图标-07.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.请假记录.setIcon(icon11)
        self.请假记录.setObjectName("请假记录")
        self.考勤记录 = QtWidgets.QAction(MainWindow)
        self.考勤记录.setObjectName("考勤记录")
        self.后勤申请 = QtWidgets.QAction(MainWindow)
        self.后勤申请.setObjectName("后勤申请")
        self.actFont_xiangmuxinxi = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("ICO/图标-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_xiangmuxinxi.setIcon(icon12)
        self.actFont_xiangmuxinxi.setObjectName("actFont_xiangmuxinxi")
        self.项目计划 = QtWidgets.QAction(MainWindow)
        self.项目计划.setObjectName("项目计划")
        self.机台安排 = QtWidgets.QAction(MainWindow)
        self.机台安排.setObjectName("机台安排")
        self.设备维修 = QtWidgets.QAction(MainWindow)
        self.设备维修.setObjectName("设备维修")
        self.产品信息 = QtWidgets.QAction(MainWindow)
        self.产品信息.setObjectName("产品信息")
        self.验模信息 = QtWidgets.QAction(MainWindow)
        self.验模信息.setObjectName("验模信息")
        self.检具管理 = QtWidgets.QAction(MainWindow)
        self.检具管理.setObjectName("检具管理")
        self.仪校管理 = QtWidgets.QAction(MainWindow)
        self.仪校管理.setObjectName("仪校管理")
        self.品质异常 = QtWidgets.QAction(MainWindow)
        self.品质异常.setObjectName("品质异常")
        self.交样信息 = QtWidgets.QAction(MainWindow)
        self.交样信息.setObjectName("交样信息")
        self.工程资料 = QtWidgets.QAction(MainWindow)
        self.工程资料.setObjectName("工程资料")
        self.详细清单 = QtWidgets.QAction(MainWindow)
        self.详细清单.setObjectName("详细清单")
        self.入库管理 = QtWidgets.QAction(MainWindow)
        self.入库管理.setObjectName("入库管理")
        self.出库管理 = QtWidgets.QAction(MainWindow)
        self.出库管理.setObjectName("出库管理")
        self.退货管理 = QtWidgets.QAction(MainWindow)
        self.退货管理.setObjectName("退货管理")
        self.借用管理 = QtWidgets.QAction(MainWindow)
        self.借用管理.setObjectName("借用管理")
        self.库存管理 = QtWidgets.QAction(MainWindow)
        self.库存管理.setObjectName("库存管理")
        self.报废清单 = QtWidgets.QAction(MainWindow)
        self.报废清单.setObjectName("报废清单")
        self.采购申请 = QtWidgets.QAction(MainWindow)
        self.采购申请.setObjectName("采购申请")
        self.品质一览 = QtWidgets.QAction(MainWindow)
        self.品质一览.setObjectName("品质一览")
        self.异常一览 = QtWidgets.QAction(MainWindow)
        self.异常一览.setObjectName("异常一览")
        self.进度一览 = QtWidgets.QAction(MainWindow)
        self.进度一览.setObjectName("进度一览")
        self.库存一览 = QtWidgets.QAction(MainWindow)
        self.库存一览.setObjectName("库存一览")
        self.截图软件 = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(3).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.截图软件.setIcon(icon13)
        self.截图软件.setObjectName("截图软件")
        self.翻译软件 = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(243).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.翻译软件.setIcon(icon14)
        self.翻译软件.setObjectName("翻译软件")
        self.日历 = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("ICO/png/1234864.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.日历.setIcon(icon15)
        self.日历.setObjectName("日历")
        self.密码修改 = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(194).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.密码修改.setIcon(icon16)
        self.密码修改.setObjectName("密码修改")
        self.账号切换 = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(269).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.账号切换.setIcon(icon17)
        self.账号切换.setObjectName("账号切换")
        self.退出 = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(240).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.退出.setIcon(icon18)
        self.退出.setObjectName("退出")
        self.皮肤 = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("ICO/1142575.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.皮肤.setIcon(icon19)
        self.皮肤.setObjectName("皮肤")
        self.采购管理 = QtWidgets.QAction(MainWindow)
        self.采购管理.setObjectName("采购管理")
        self.外协管理 = QtWidgets.QAction(MainWindow)
        self.外协管理.setObjectName("外协管理")
        self.报销申请 = QtWidgets.QAction(MainWindow)
        self.报销申请.setObjectName("报销申请")
        self.体系查询 = QtWidgets.QAction(MainWindow)
        self.体系查询.setObjectName("体系查询")
        self.体系修改 = QtWidgets.QAction(MainWindow)
        self.体系修改.setObjectName("体系修改")
        self.actioncsdc = QtWidgets.QAction(MainWindow)
        self.actioncsdc.setObjectName("actioncsdc")
        self.ren_shi.addAction(self.actFont_ranyuanchaxun)
        self.ren_shi.addAction(self.请假记录)
        self.ren_shi.addAction(self.加班记录)
        self.ren_shi.addAction(self.考勤记录)
        self.ren_shi.addAction(self.后勤申请)
        self.xiang_mu.addAction(self.actFont_xiangmuxinxi)
        self.xiang_mu.addAction(self.项目计划)
        self.sheng_chan.addAction(self.工程资料)
        self.sheng_chan.addAction(self.机台安排)
        self.sheng_chan.addAction(self.设备维修)
        self.pin_zhi.addAction(self.产品信息)
        self.pin_zhi.addAction(self.验模信息)
        self.pin_zhi.addAction(self.检具管理)
        self.pin_zhi.addAction(self.仪校管理)
        self.pin_zhi.addAction(self.品质异常)
        self.pin_zhi.addAction(self.交样信息)
        self.chang_ku.addAction(self.详细清单)
        self.chang_ku.addAction(self.入库管理)
        self.chang_ku.addAction(self.出库管理)
        self.chang_ku.addAction(self.退货管理)
        self.chang_ku.addAction(self.借用管理)
        self.chang_ku.addAction(self.库存管理)
        self.chang_ku.addAction(self.报废清单)
        self.cai_wu.addAction(self.采购申请)
        self.cai_wu.addAction(self.报销申请)
        self.cai_wu.addSeparator()
        self.cai_wu.addAction(self.采购管理)
        self.cai_wu.addAction(self.外协管理)
        self.ti_xi.addAction(self.体系查询)
        self.ti_xi.addAction(self.体系修改)
        self.zong_he_fen_xi.addAction(self.品质一览)
        self.zong_he_fen_xi.addAction(self.异常一览)
        self.zong_he_fen_xi.addAction(self.进度一览)
        self.zong_he_fen_xi.addAction(self.库存一览)
        self.chang_yong_ruan_jian.addAction(self.截图软件)
        self.chang_yong_ruan_jian.addAction(self.翻译软件)
        self.chang_yong_ruan_jian.addAction(self.日历)
        self.bang_zhu.addAction(self.密码修改)
        self.bang_zhu.addAction(self.账号切换)
        self.bang_zhu.addAction(self.退出)
        self.bang_zhu.addSeparator()
        self.bang_zhu.addAction(self.皮肤)
        self.caidan.addAction(self.ren_shi.menuAction())
        self.caidan.addAction(self.xiang_mu.menuAction())
        self.caidan.addAction(self.sheng_chan.menuAction())
        self.caidan.addAction(self.pin_zhi.menuAction())
        self.caidan.addAction(self.chang_ku.menuAction())
        self.caidan.addAction(self.cai_wu.menuAction())
        self.caidan.addAction(self.ti_xi.menuAction())
        self.caidan.addAction(self.zong_he_fen_xi.menuAction())
        self.caidan.addAction(self.chang_yong_ruan_jian.menuAction())
        self.caidan.addAction(self.bang_zhu.menuAction())
        self.toolBar.addAction(self.actFont_ranyuanchaxun)
        self.toolBar.addAction(self.actFont_xiangmuxinxi)
        self.toolBar.addAction(self.加班记录)
        self.toolBar.addAction(self.请假记录)

        self.retranslateUi(MainWindow)
        self.ZhuCaiDan.setCurrentIndex(2)
        QtCore.QObject.connect(self.退出, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "飞云信息管理平台", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.ranwu), QtWidgets.QApplication.translate("MainWindow", "任务栏", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.zhicaidan), QtWidgets.QApplication.translate("MainWindow", "子菜单", None, -1))
        self.ryxx_tuichu.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.ryxx_chakan.setText(QtWidgets.QApplication.translate("MainWindow", "查看", None, -1))
        self.ryxx_xinzeng.setText(QtWidgets.QApplication.translate("MainWindow", "新增", None, -1))
        self.ryxx_xiugai.setText(QtWidgets.QApplication.translate("MainWindow", "修改", None, -1))
        self.ryxx_liuchengtiaozhuan.setText(QtWidgets.QApplication.translate("MainWindow", "流程跳转", None, -1))
        self.ryxx_shanchu.setText(QtWidgets.QApplication.translate("MainWindow", "删除", None, -1))
        self.ryxx_daochu.setText(QtWidgets.QApplication.translate("MainWindow", "导出", None, -1))
        self.ryxx_chaxun.setText(QtWidgets.QApplication.translate("MainWindow", "查询", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "日期：", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "部门：", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "工号：", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "姓名：", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "至", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "筛选方式：", None, -1))
        self.ryxx_shaixuan.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "在职人员", None, -1))
        self.ryxx_shaixuan.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "入职日期", None, -1))
        self.ryxx_shaixuan.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "生日日期", None, -1))
        self.ryxx_shaixuan.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "离职人员", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.renyuanxinxi), QtWidgets.QApplication.translate("MainWindow", "人员信息", None, -1))
        self.xmxx_tuichu.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.xmxx_liuchengtiaozhuan.setText(QtWidgets.QApplication.translate("MainWindow", "流程跳转", None, -1))
        self.xmxx_daochu.setText(QtWidgets.QApplication.translate("MainWindow", "导出", None, -1))
        self.xmxx_xiugai.setText(QtWidgets.QApplication.translate("MainWindow", "修改", None, -1))
        self.xmxx_xinzeng.setText(QtWidgets.QApplication.translate("MainWindow", "新增", None, -1))
        self.xmxx_chakan.setText(QtWidgets.QApplication.translate("MainWindow", "查看", None, -1))
        self.xmxx_shanchu.setText(QtWidgets.QApplication.translate("MainWindow", "删除", None, -1))
        self.xmxx_chaxun.setText(QtWidgets.QApplication.translate("MainWindow", "查询", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "日期：", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "客户：", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "模号：", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "至", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "筛选方式：", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "业务", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "项目", None, -1))
        self.comboBox_2.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "设计", None, -1))
        self.comboBox_2.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "钳工", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "客户编号：", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "担当人：", None, -1))
        self.xmxx_shaixuan.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "下单", None, -1))
        self.xmxx_shaixuan.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "首样", None, -1))
        self.xmxx_shaixuan.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "移模", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "包括移模项目", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "包括历史记录", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "序号", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "内部编号", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "客户编号", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "产品等级", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "业务担当", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "项目担当", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "设计担当", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "现场担当", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "组别", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "下单日期", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(10).setText(QtWidgets.QApplication.translate("MainWindow", "首样日期", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(11).setText(QtWidgets.QApplication.translate("MainWindow", "要求移模日期", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(12).setText(QtWidgets.QApplication.translate("MainWindow", "实际移模日期", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(13).setText(QtWidgets.QApplication.translate("MainWindow", "合格/特采", None, -1))
        self.xmxx_tableWidget.horizontalHeaderItem(14).setText(QtWidgets.QApplication.translate("MainWindow", "备注", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.xiangmuxinxi), QtWidgets.QApplication.translate("MainWindow", "项目信息", None, -1))
        self.toolButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.toolButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "查看", None, -1))
        self.toolButton_17.setText(QtWidgets.QApplication.translate("MainWindow", "修改", None, -1))
        self.toolButton_18.setText(QtWidgets.QApplication.translate("MainWindow", "流程跳转", None, -1))
        self.toolButton_19.setText(QtWidgets.QApplication.translate("MainWindow", "删除", None, -1))
        self.toolButton_20.setText(QtWidgets.QApplication.translate("MainWindow", "导出", None, -1))
        self.toolButton_21.setText(QtWidgets.QApplication.translate("MainWindow", "新增", None, -1))
        self.chaxun_3.setText(QtWidgets.QApplication.translate("MainWindow", "查询", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "日期：", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "客户：", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "模号：", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "至", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "客户编号：", None, -1))
        self.checkBox_5.setText(QtWidgets.QApplication.translate("MainWindow", "包括移模项目", None, -1))
        self.checkBox_6.setText(QtWidgets.QApplication.translate("MainWindow", "包括历史记录", None, -1))
        self.comboBox_18.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "样品", None, -1))
        self.comboBox_18.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "零件", None, -1))
        self.comboBox_18.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "检具", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "类型：", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "检测人员：", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.jiancebaogao), QtWidgets.QApplication.translate("MainWindow", "检测报告", None, -1))
        self.toolButton_22.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.toolButton_23.setText(QtWidgets.QApplication.translate("MainWindow", "查看", None, -1))
        self.toolButton_24.setText(QtWidgets.QApplication.translate("MainWindow", "修改", None, -1))
        self.toolButton_25.setText(QtWidgets.QApplication.translate("MainWindow", "流程跳转", None, -1))
        self.toolButton_26.setText(QtWidgets.QApplication.translate("MainWindow", "删除", None, -1))
        self.toolButton_27.setText(QtWidgets.QApplication.translate("MainWindow", "导出", None, -1))
        self.toolButton_28.setText(QtWidgets.QApplication.translate("MainWindow", "新增", None, -1))
        self.chaxun_4.setText(QtWidgets.QApplication.translate("MainWindow", "查询", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "日期：", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "客户：", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "模号：", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "至", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "客户编号：", None, -1))
        self.checkBox_7.setText(QtWidgets.QApplication.translate("MainWindow", "包括移模项目", None, -1))
        self.checkBox_8.setText(QtWidgets.QApplication.translate("MainWindow", "包括历史记录", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "验收人员：", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.yanmoxingxi), QtWidgets.QApplication.translate("MainWindow", "验模信息", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "记事本", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.jishiben), QtWidgets.QApplication.translate("MainWindow", "记事本", None, -1))
        self.ren_shi.setTitle(QtWidgets.QApplication.translate("MainWindow", "人事管理", None, -1))
        self.xiang_mu.setTitle(QtWidgets.QApplication.translate("MainWindow", "项目管理", None, -1))
        self.sheng_chan.setTitle(QtWidgets.QApplication.translate("MainWindow", "生产管理", None, -1))
        self.pin_zhi.setTitle(QtWidgets.QApplication.translate("MainWindow", "品质管理", None, -1))
        self.chang_ku.setTitle(QtWidgets.QApplication.translate("MainWindow", "仓库管理", None, -1))
        self.cai_wu.setTitle(QtWidgets.QApplication.translate("MainWindow", "财务管理", None, -1))
        self.ti_xi.setTitle(QtWidgets.QApplication.translate("MainWindow", "体系管理", None, -1))
        self.zong_he_fen_xi.setTitle(QtWidgets.QApplication.translate("MainWindow", "综合分析", None, -1))
        self.chang_yong_ruan_jian.setTitle(QtWidgets.QApplication.translate("MainWindow", "常用软件", None, -1))
        self.bang_zhu.setTitle(QtWidgets.QApplication.translate("MainWindow", "帮助", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actFont_ranyuanchaxun.setText(QtWidgets.QApplication.translate("MainWindow", "人员查询", None, -1))
        self.加班记录.setText(QtWidgets.QApplication.translate("MainWindow", "加班记录", None, -1))
        self.请假记录.setText(QtWidgets.QApplication.translate("MainWindow", "请假记录", None, -1))
        self.考勤记录.setText(QtWidgets.QApplication.translate("MainWindow", "考勤记录", None, -1))
        self.后勤申请.setText(QtWidgets.QApplication.translate("MainWindow", "后勤申请", None, -1))
        self.actFont_xiangmuxinxi.setText(QtWidgets.QApplication.translate("MainWindow", "项目信息", None, -1))
        self.项目计划.setText(QtWidgets.QApplication.translate("MainWindow", "项目计划", None, -1))
        self.机台安排.setText(QtWidgets.QApplication.translate("MainWindow", "机台安排", None, -1))
        self.设备维修.setText(QtWidgets.QApplication.translate("MainWindow", "设备维修", None, -1))
        self.产品信息.setText(QtWidgets.QApplication.translate("MainWindow", "产品信息", None, -1))
        self.产品信息.setToolTip(QtWidgets.QApplication.translate("MainWindow", "产品信息", None, -1))
        self.验模信息.setText(QtWidgets.QApplication.translate("MainWindow", "验模信息", None, -1))
        self.验模信息.setToolTip(QtWidgets.QApplication.translate("MainWindow", "验模信息", None, -1))
        self.检具管理.setText(QtWidgets.QApplication.translate("MainWindow", "检具管理", None, -1))
        self.仪校管理.setText(QtWidgets.QApplication.translate("MainWindow", "仪校管理", None, -1))
        self.品质异常.setText(QtWidgets.QApplication.translate("MainWindow", "品质异常", None, -1))
        self.交样信息.setText(QtWidgets.QApplication.translate("MainWindow", "交样信息", None, -1))
        self.工程资料.setText(QtWidgets.QApplication.translate("MainWindow", "工程资料", None, -1))
        self.详细清单.setText(QtWidgets.QApplication.translate("MainWindow", "详细清单", None, -1))
        self.入库管理.setText(QtWidgets.QApplication.translate("MainWindow", "入库管理", None, -1))
        self.出库管理.setText(QtWidgets.QApplication.translate("MainWindow", "出库管理", None, -1))
        self.退货管理.setText(QtWidgets.QApplication.translate("MainWindow", "退货管理", None, -1))
        self.借用管理.setText(QtWidgets.QApplication.translate("MainWindow", "借用管理", None, -1))
        self.库存管理.setText(QtWidgets.QApplication.translate("MainWindow", "库存管理", None, -1))
        self.报废清单.setText(QtWidgets.QApplication.translate("MainWindow", "报废清单", None, -1))
        self.采购申请.setText(QtWidgets.QApplication.translate("MainWindow", "采购申请", None, -1))
        self.品质一览.setText(QtWidgets.QApplication.translate("MainWindow", "品质一览", None, -1))
        self.异常一览.setText(QtWidgets.QApplication.translate("MainWindow", "异常一览", None, -1))
        self.进度一览.setText(QtWidgets.QApplication.translate("MainWindow", "进度一览", None, -1))
        self.库存一览.setText(QtWidgets.QApplication.translate("MainWindow", "库存一览", None, -1))
        self.截图软件.setText(QtWidgets.QApplication.translate("MainWindow", "截图软件", None, -1))
        self.翻译软件.setText(QtWidgets.QApplication.translate("MainWindow", "翻译软件", None, -1))
        self.日历.setText(QtWidgets.QApplication.translate("MainWindow", "日历", None, -1))
        self.密码修改.setText(QtWidgets.QApplication.translate("MainWindow", "密码修改", None, -1))
        self.密码修改.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.账号切换.setText(QtWidgets.QApplication.translate("MainWindow", "账号切换", None, -1))
        self.账号切换.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.退出.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.退出.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "点击按钮退出程序！", None, -1))
        self.退出.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.皮肤.setText(QtWidgets.QApplication.translate("MainWindow", "皮肤", None, -1))
        self.采购管理.setText(QtWidgets.QApplication.translate("MainWindow", "采购管理", None, -1))
        self.外协管理.setText(QtWidgets.QApplication.translate("MainWindow", "外协管理", None, -1))
        self.报销申请.setText(QtWidgets.QApplication.translate("MainWindow", "报销申请", None, -1))
        self.体系查询.setText(QtWidgets.QApplication.translate("MainWindow", "体系查询", None, -1))
        self.体系修改.setText(QtWidgets.QApplication.translate("MainWindow", "体系修改", None, -1))
        self.actioncsdc.setText(QtWidgets.QApplication.translate("MainWindow", "csdc", None, -1))

